version: "3.9"
services:
  api-service:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - model-service
    
  model-service:
    build: ./model
    ports:
      - "8001:8001"

  redis:
    image: redis:6.2.6
